In [5]:
print("Hello world")

Hello world


In [6]:
string = "Python"
string*2

'PythonPython'

In [7]:
string = "Great Learning"
string[23]

IndexError: string index out of range

In [ ]:
string = "Great Learning"
string[0:5]

'Great'

Python indexes Lists and Tuples at 0, but using methods like .insert it indexes at 1

In [ ]:
my_tuple = ("hello", "get")
sorted(my_tuple)

['get', 'hello']

In [ ]:
my_tuple = ("hello", "get", 1, 2, 3)
sorted(my_tuple)

TypeError: '<' not supported between instances of 'int' and 'str'

sorted() cannot sort a mixture of strings and numbers, but it can sort one or the other

In [ ]:
list1 = [1,2,3,4,5]

list2 = list1

list2.append(19)

print(list1)
print(list2)

[1, 2, 3, 4, 5, 19]
[1, 2, 3, 4, 5, 19]


In python, copying a list or dictionary like:

list2 = list1

Is bad practice as you're assigning the reference to list1 as the value in list2. Meaning if you change list1 or list2, they both are changed. The correct way to copy a list or dictionary is to use the copy method

In [8]:
list1 = [1,2,3,4,5]

list2 = list1.copy()

list2.append(19)

print(list1)
print(list2)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 19]


In [2]:
[int(char) for char in str(807)[::-1]]

[7, 0, 8]

In [8]:
nums = [0,1,0,3,12]

count = nums.count(0)
print(len(nums))

5


In [12]:
import numpy as np

print(np.cos(np.sin([3,1,4,34])))

[0.99005909 0.66636675 0.72703513 0.86327044]


In [18]:
# defining two arrays
arr7 = np.arange(1,6)
print('arr7:', arr7)

arr8 = np.arange(3,8)
print('arr8:', arr8)

arr7: [1 2 3 4 5]
arr8: [3 4 5 6 7]


In [20]:
print(arr7 + arr8)
print(arr7 ^ arr8)

[ 4  6  8 10 12]
[2 6 6 2 2]


In [3]:
import numpy as np

mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1] = 5
print(mat)

[[1 2 1]
 [5 5 5]
 [1 8 9]]


In [4]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
print('Multiplication: \n', n1 @ n2)

Multiplication: 
 [[1786 1880 3017]
 [2725 2933 4712]
 [3862 4220 6785]]


In [58]:
import pandas as pd

df = pd.read_csv("./PythonFoundations/books.csv")

df.loc[[0,4],['language_code', 'num_pages', 'ratings_count']]

df.groupby(["author"])["average_rating"].mean()

author
A.D.P. Briggs         3.760000
A.E. Cunningham       4.150000
A.N. Roquelaure       3.620000
A.S. Byatt            3.770000
Abdul Rahman Munif    4.130000
                        ...   
Zora Neale Hurston    4.052500
Zoë Heller            3.710000
bell hooks            4.275000
Åsne Seierstad        3.765000
Émile Zola            3.866667
Name: average_rating, Length: 2453, dtype: float64